
obj-$(CONFIG_INFINIBAND_IBTRS_CLT)	+= ibtrs_client.o

ibtrs_client-y		:= ibtrs_clt.o ibtrs_clt_sysfs.o \
	../ibtrs_lib/ibtrs.o ../ibtrs_lib/ibtrs-proto.o ../ibtrs_lib/iu.o \
	../ibtrs_lib/heartbeat.o ../ibtrs_lib/common.o
