
obj-$(CONFIG_INFINIBAND_IBTRS_SRV)	+= ibtrs_server.o

ibtrs_server-y		:= ibtrs_srv.o ibtrs_srv_sysfs.o \
			   ../ibtrs_lib/ibtrs.o ../ibtrs_lib/ibtrs-proto.o ../ibtrs_lib/iu.o \
			   ../ibtrs_lib/heartbeat.o ../ibtrs_lib/common.o
